# Generated by Django 5.2.17 on 2026-08-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
