# Generated by Django 5.2.17 on 2026-08-19 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='order',
        ),
    ]
