# Generated by Django 5.2.17 on 2026-08-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_remove_stat_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stat',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='stat',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
