# Generated by Django 5.2.17 on 2026-08-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.PositiveIntegerField(default=2026),
            preserve_default=False,
        ),
    ]
