# Generated by Django 5.2.17 on 2026-08-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='scope',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
