# Generated by Django 5.2.17 on 2026-08-19 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'ordering': ['step']},
        ),
        migrations.RemoveField(
            model_name='process',
            name='order',
        ),
    ]
