# Generated by Django 5.2.17 on 2026-08-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home_delete_hero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='home',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
