# Generated by Django 5.2.17 on 2026-08-19 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='established_year',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='location',
        ),
    ]
