# Generated by Django 5.2.17 on 2026-08-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_remove_practice_established_year_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practice',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='practice',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
