# Generated by Django 5.2.17 on 2026-08-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='category',
        ),
        migrations.AlterField(
            model_name='review',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('video', 'Video')], max_length=10),
        ),
        migrations.DeleteModel(
            name='ReviewCategory',
        ),
    ]
