# Generated by Django 5.2.17 on 2026-08-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_review_category_alter_review_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
